import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.HSA_PLAYWRIGHT||'playwright-core');
const base='http://127.0.0.1:4317';
const cats=vm.runInNewContext(fs.readFileSync('assets/data.js','utf8')+';CATEGORIES');
fs.mkdirSync('docs/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true});
let assertions=0;const errors=[],checks=[];
const assert=(condition,msg)=>{assertions++;if(!condition)throw Error(msg);checks.push(msg);};
const stub=(mode)=>`window.supabase={createClient(){const session=${mode==='guest'?'null':JSON.stringify({user:{id:'qa-user',email:'qa@example.test'},expires_at:9999999999,access_token:'qa-test-token'})};const profile=${JSON.stringify(mode==='paid'?{is_paid:true,is_admin:false}:mode==='admin'?{is_paid:false,is_admin:true}:{is_paid:false,is_admin:false})};return {auth:{getSession:async()=>({data:{session}}),refreshSession:async()=>({data:{session}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({}),signInWithPassword:async()=>({error:null}),signUp:async()=>({data:{session:null},error:null}),signInWithOAuth:async()=>({error:null})},from:()=>({select:()=>({eq:()=>({single:async()=>({data:profile})})})})};}};`;
async function context(mode,width=1440){const c=await browser.newContext({viewport:{width,height:1000},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});await c.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:stub(mode)}));await c.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));const p=await c.newPage();p.on('pageerror',err=>errors.push(mode+': '+err.message));return {c,p};}
async function overflow(p,label){const d=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(d.scroll<=d.width+1,label+' no horizontal overflow');}
try{
 const {c,p}=await context('guest');
 await p.goto(base);await p.waitForSelector('.course-tile');assert(await p.locator('.course-tile').count()===7,'Home has 7 courses');await overflow(p,'Desktop home');await p.screenshot({path:'docs/screenshots/home-desktop.png',fullPage:true});
 await p.locator('#searchInput').fill('Canva');assert(await p.locator('.lesson-row').count()>0,'Search finds Canva');await p.locator('#searchInput').fill('該当なしzzzz');assert(await p.locator('.empty-state').isVisible(),'Empty search message');await p.locator('[data-reset]').click();await p.locator('#courseSelect').selectOption('basic');assert(await p.locator('.lesson-row').count()===11,'Basic course has 11 lessons');
 await p.locator('[data-bookmark="basic-0"]').click();await p.locator('#filterSelect').selectOption('bookmark');assert(await p.locator('.lesson-row').count()===1,'Bookmark filter');await p.reload();assert(await p.locator('#bookmarkCount').textContent()==='1','Bookmark persists');
 await p.goto(base+'/lessons/basic-1.html');await p.locator('#studyNote').fill('QA：次回は保存の確認から始める。');await p.locator('[data-check="0"]').check();await p.locator('.complete-btn').click();assert(await p.locator('.complete-btn').getAttribute('aria-pressed')==='true','Complete state toggles');await p.reload();assert(await p.locator('#studyNote').inputValue()==='QA：次回は保存の確認から始める。','Note persists after reload');assert(await p.locator('[data-check="0"]').isChecked(),'Checklist persists');await p.locator('[data-copy]').click();assert((await p.evaluate(()=>navigator.clipboard.readText())).includes('機器名'),'Template clipboard copy');const download=p.waitForEvent('download');await p.locator('[data-download]').click();const file=await download;await file.saveAs('docs/qa-note.txt');assert(fs.readFileSync('docs/qa-note.txt','utf8').includes('次回は保存'),'Note download contents');
 await p.locator('[data-size]').click();assert(await p.locator('body').evaluate(el=>el.classList.contains('large-text')),'Large text toggle');await overflow(p,'Desktop large-text reader');await p.screenshot({path:'docs/screenshots/reader-desktop.png',fullPage:true});
 await p.goto(base);assert((await p.locator('#doneCount').textContent()).startsWith('1'),'Dashboard reports learning completion, not publication');await p.locator('#filterSelect').selectOption('done');assert(await p.locator('.lesson-row').count()===1,'Completed filter');
 await p.goto(base+'/lessons/image-2.html');await p.waitForSelector('.lesson-lock-h');assert(await p.locator('.article').count()===0,'Guest paid content removed');assert(await p.locator('.reader-toc').count()===0,'Guest paid TOC removed');await p.screenshot({path:'docs/screenshots/locked-desktop.png'});
 await p.goto(base+'/lessons/image-1.html');assert(await p.locator('.article').isVisible(),'Guest can access first skill lesson');
 await c.close();
 const mobile=await context('guest',390);await mobile.p.goto(base);await mobile.p.waitForSelector('.course-tile');await overflow(mobile.p,'390px home');assert(await mobile.p.locator('#sidebar').evaluate(el=>el.inert),'Closed mobile menu is inert');await mobile.p.screenshot({path:'docs/screenshots/home-mobile.png',fullPage:true});await mobile.p.locator('#menuButton').click();assert(await mobile.p.locator('#menuButton').getAttribute('aria-expanded')==='true','Mobile menu opens');await mobile.p.locator('#courseNav [data-course="writing"]').click();assert(await mobile.p.locator('.lesson-row').count()===10,'Mobile course navigation');assert(await mobile.p.locator('#menuButton').getAttribute('aria-expanded')==='false','Mobile menu closes after selection');await overflow(mobile.p,'390px course list');await mobile.p.screenshot({path:'docs/screenshots/course-mobile.png',fullPage:true});await mobile.p.goto(base+'/lessons/basic-1.html');assert(!await mobile.p.locator('#tocDetails').evaluate(el=>el.open),'Mobile TOC starts closed');await mobile.p.locator('#tocDetails summary').click();await mobile.p.locator('.reader-toc nav a').nth(3).click();assert(!await mobile.p.locator('#tocDetails').evaluate(el=>el.open),'Mobile TOC closes after jump');await mobile.p.locator('[data-size]').click();await overflow(mobile.p,'390px large text');await mobile.p.screenshot({path:'docs/screenshots/reader-mobile.png',fullPage:true});await mobile.c.close();
 const paid=await context('paid',390);for(const cat of cats){for(const lesson of cat.lessons){await paid.p.goto(base+'/'+lesson.url);await paid.p.waitForSelector('.article',{state:'visible'});assert(await paid.p.locator('h1').count()===1,lesson.url+' H1');assert(await paid.p.locator('.worksheet').count()===1,lesson.url+' worksheet');assert(await paid.p.locator('.checklist input').count()===3,lesson.url+' checklist');await overflow(paid.p,lesson.url+' mobile');const anchors=await paid.p.locator('.reader-toc nav a').evaluateAll(links=>links.every(a=>document.getElementById(a.hash.slice(1))));assert(anchors,lesson.url+' TOC targets');}}
 await paid.p.goto(base+'/lessons/sales-10.html');await paid.p.locator('#studyNote').fill('QA paid lesson note');await paid.p.reload();assert(await paid.p.locator('#studyNote').inputValue()==='QA paid lesson note','Paid reader activates after authorization');await paid.p.locator('.complete-btn').click();assert(await paid.p.locator('.complete-btn').getAttribute('aria-pressed')==='true','Paid completion works');await paid.p.setViewportSize({width:320,height:780});await overflow(paid.p,'320px paid reader');await paid.p.screenshot({path:'docs/screenshots/reader-320.png',fullPage:true});await paid.p.goto(base);await overflow(paid.p,'320px home');await paid.c.close();
 for(const mode of ['unpaid','admin']){const {c,p}=await context(mode);await p.goto(base+'/lessons/ai-4.html');if(mode==='unpaid'){await p.waitForSelector('.lesson-lock-h');assert(await p.locator('.article').count()===0,'Unpaid member content locked');assert(await p.locator('#hsaLockBuy').isVisible(),'Unpaid member has purchase action');}else{await p.waitForSelector('.lesson-admin-bar');assert(await p.locator('.article').isVisible(),'Admin preview visible');}await c.close();}
 const offline=await browser.newContext({viewport:{width:390,height:844}});await offline.route('https://**',r=>r.abort());const op=await offline.newPage();op.on('pageerror',err=>errors.push('offline: '+err.message));await op.goto(base);await op.waitForSelector('.course-tile');assert(await op.locator('.course-tile').count()===7,'Auth unavailable: home still works');await op.goto(base+'/lessons/basic-1.html');await op.locator('#studyNote').fill('offline SDK note');await op.reload();assert(await op.locator('#studyNote').inputValue()==='offline SDK note','Auth unavailable: free reader saves notes');await offline.close();
 assert(errors.length===0,'No browser page errors: '+errors.join('; '));
 fs.writeFileSync('docs/browser-check.json',JSON.stringify({date:new Date().toISOString(),assertions,errors,auth:'Synthetic guest/unpaid/paid/admin Supabase responses; no live login or payment performed.',checks},null,2)+'\n');console.log('PASS '+assertions+' assertions; all 71 readers checked at 390px.');
}catch(err){fs.writeFileSync('docs/browser-failure.json',JSON.stringify({error:err.message,errors,assertions},null,2));throw err;}finally{await browser.close();}
