import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.HSA_PLAYWRIGHT||'playwright-core');
const browser=await chromium.launch({headless:true});const base='http://127.0.0.1:4317';const errors=[],checks=[];
const assert=(x,msg)=>{if(!x)throw Error(msg+'; browser errors: '+errors.join('; '));checks.push(msg);};
const guest=`window.supabase={createClient(){return {auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>({}),signInWithPassword:async()=>({error:null}),signUp:async()=>({data:{session:null},error:null}),signOut:async()=>({}),signInWithOAuth:async()=>({error:null})}}}};`;
try{
const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await ctx.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:guest}));await ctx.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'/login.html?next=lessons/image-2.html');await p.locator('[data-mode="signup"]').click();assert(await p.locator('#password').getAttribute('autocomplete')==='new-password','Signup password autocomplete');await p.locator('#email').fill('qa@example.test');await p.locator('#password').fill('synthetic-test-value');await p.locator('#submit').click();assert((await p.locator('#msg').textContent()).includes('確認メール'),'Synthetic signup confirmation');await p.screenshot({path:'docs/screenshots/login-mobile.png'});await p.locator('[data-mode="login"]').click();await p.locator('#submit').click();await p.waitForURL('**/lessons/image-2.html');assert(await p.locator('.lesson-lock-h').isVisible(),'Login returns to requested lesson (synthetic session)');
await p.goto(base+'/login.html?next=https://example.org');assert(await p.evaluate(()=>nextParam)==='index.html','External redirect rejected');
await p.goto(base);await p.locator('#menuButton').click();await p.locator('#courseNav [data-course="web"]').click();assert(await p.evaluate(()=>document.activeElement.id)==='menuButton','Menu restores focus');await p.screenshot({path:'docs/screenshots/course-mobile-viewport.png'});await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:'docs/screenshots/home-mobile-viewport.png'});
await p.goto(base+'/lessons/basic-1.html');await p.screenshot({path:'docs/screenshots/reader-mobile-top.png'});await p.locator('.worked-example').scrollIntoViewIfNeeded();await p.screenshot({path:'docs/screenshots/reader-mobile-example.png'});await p.locator('.notes-section').scrollIntoViewIfNeeded();await p.screenshot({path:'docs/screenshots/reader-mobile-notes.png'});
await p.locator('#studyNote').fill('続きから再開のテスト');await p.locator('.worked-example h2').scrollIntoViewIfNeeded();await p.waitForTimeout(150);const last=await p.evaluate(()=>Study.read('hsa_last',null));await p.goto(base);assert((await p.locator('#resumeLink').getAttribute('href')).includes('basic-1.html'),'Resume points to last unfinished lesson');assert((await p.locator('#resumeLink').textContent()).includes('続き'),'Resume label');
await p.setViewportSize({width:1440,height:1000});await p.goto(base+'/lessons/writing-1.html');await p.screenshot({path:'docs/screenshots/reader-desktop-top.png'});await p.locator('.worked-example').scrollIntoViewIfNeeded();await p.screenshot({path:'docs/screenshots/reader-desktop-example.png'});await ctx.close();
const denied=await browser.newContext({viewport:{width:390,height:844}});await denied.route(/^https:/,r=>r.abort());await denied.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError')};});const dp=await denied.newPage();dp.on('pageerror',e=>errors.push(e.message));await dp.goto(base+'/lessons/basic-1.html');await dp.locator('.complete-btn').click();assert(await dp.locator('.complete-btn').getAttribute('aria-pressed')==='true','Storage denied: session state still updates');assert((await dp.locator('#toast').textContent()).includes('保存できません'),'Storage denied: visible warning');await dp.locator('#studyNote').fill('保存できない場合');assert((await dp.locator('#noteStatus').textContent()).includes('保存できません'),'Storage denied: note export guidance');await dp.goto(base+'/login.html');assert(await dp.locator('#submit').isDisabled(),'SDK unavailable: login disabled');assert((await dp.locator('#msg').textContent()).includes('接続できません'),'SDK unavailable: login explains failure');await denied.close();
assert(errors.length===0,'No additional browser errors');fs.writeFileSync('docs/final-check.json',JSON.stringify({date:new Date().toISOString(),checks,errors,note:'Synthetic authentication only; no real email, signup, or checkout.'},null,2)+'\n');console.log('PASS '+checks.length+' focused checks.');
}finally{await browser.close();}
